
# logging
logging:
    level:
        org.springframework: WARN
        com.cloudolp.peony.server: DEBUG
    config: classpath:logback.xml
    #file: /var/log/cloudolp/essential-user.log
#Common properties

#database
spring:
    datasource:
        url: jdbc:mysql://10.0.5.184/mvp_mall_new?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=round
        username: root
        password: admin
server:
  port: 8080

#wechat pay config
wechat:
    pay:
        config:
            domain: baidu.com
            appId: 123
            mchId: sdfdf
            key: 15544